spring:
  application:
    name: Gateway

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  prefix: "/api"
  ignored-services: '*'
  routes:
    gallery:
        path: /gallery/**
        service-id: GalleryService